sudo: required
services:
  - docker

before_install:
  - docker build -t enginbulut/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true enginbulut/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-541424051176"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret-access_key:
    secure: "$AWS_SECRET_KEY"